# Generated by Django 5.2.3 on 2026-07-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.CharField(help_text='OPIS Truckstop ID from the source data.', max_length=20, unique=True)),
                ('truckstop_name', models.CharField(help_text='Name of the truck stop.', max_length=255)),
                ('address', models.CharField(help_text='Street address of the truck stop.', max_length=255)),
                ('city', models.CharField(db_index=True, help_text='City where the truck stop is located.', max_length=100)),
                ('state', models.CharField(db_index=True, help_text='Two-letter state code.', max_length=2)),
                ('retail_price', models.DecimalField(decimal_places=3, help_text='Retail price per gallon of fuel.', max_digits=6)),
                ('latitude', models.FloatField(blank=True, help_text='Geocoded latitude coordinate.', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Geocoded longitude coordinate.', null=True)),
            ],
            options={
                'ordering': ['state', 'city', 'truckstop_name'],
                'indexes': [models.Index(fields=['city', 'state'], name='routing_fue_city_c91742_idx'), models.Index(fields=['latitude', 'longitude'], name='routing_fue_latitud_6dc999_idx'), models.Index(fields=['retail_price'], name='routing_fue_retail__e50bf6_idx')],
            },
        ),
    ]
